name: CI/CD Pipeline with Heroku Deploy & Slack 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build app
        run: |
          mkdir -p docs
          echo "<h1>Build $(date)</h1>" > docs/index.html

      - name: Reemplazar valores dinámicos en index.html
        run: |
          sed -i "s|const branch = \".*\";|const branch = \"${GITHUB_REF_NAME}\";|" docs/index.html
          sed -i "s|const commitSha = \".*\";|const commitSha = \"${GITHUB_SHA}\";|" docs/index.html
          sed -i "s|const repoUrl = \".*\";|const repoUrl = \"https://github.com/${GITHUB_REPOSITORY}\";|" docs/index.html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: docs

  deploy:
    name: Deploy to Heroku ✅
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-artifact
          path: docs

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

  notify-success:
    if: success()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify Slack of Success
        uses: 8398a7/action-slack@v3
        with:
          status: success
          custom_payload: |
            {
              "text": ":tada: *Pipeline exitoso!* :rocket:\nRepositorio: *${{ github.repository }}*\nCommit: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\nBranch: ${{ github.ref_name }}\nDespliegue: *completado correctamente*."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify Slack of Failure
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          custom_payload: |
            {
              "text": ":x: *Pipeline fallido!* :warning:\nRepositorio: *${{ github.repository }}*\nCommit: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\nBranch: ${{ github.ref_name }}\nPor favor, revisa los logs para más detalles."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  create-issue-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Create GitHub Issue on Deployment Failure
        uses: peter-evans/create-issue@v4
        with:
          title: "🚨 Deployment failed on main branch"
          body: |
            **Descripción:**  
            La etapa de *despliegue* en el pipeline falló.

            **Repositorio:** ${{ github.repository }}  
            **Commit:** ${{ github.sha }}  
            **Branch:** ${{ github.ref_name }}  

            Por favor, revisa los logs para investigar el problema.

            ---
            _Esta issue fue creada automáticamente por el workflow de CI/CD._
          labels: bug, deployment-failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
