name: CI/CD Pipeline with Heroku Deploy & Slack 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build app
        run: |
          mkdir -p docs
          echo "<h1>Build $(date)</h1>" > docs/index.html
      - name: Insert dynamic values in index.html
        run: |
          sed -i "s|const branch = \".*\";|const branch = \"${GITHUB_REF_NAME}\";|" docs/index.html
          sed -i "s|const commitSha = \".*\";|const commitSha = \"${GITHUB_SHA}\";|" docs/index.html
          sed -i "s|const repoUrl = \".*\";|const repoUrl = \"https://github.com/${GITHUB_REPOSITORY}\";|" docs/index.html
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: docs

  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-artifact
          path: docs
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          custom_payload: |
            {
              "text": "{{#success}}:tada: *Pipeline exitoso!*{{/success}}{{#failure}}:x: *Pipeline fallido!*{{/failure}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  create-issue:
    if: failure()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create issue content
        run: |
          cat <<EOF > my-issue.md
          ## 🚨 Deployment failed on main branch

          **Descripción:** La etapa de *despliegue* falló.
          - **Repositorio:** ${{ github.repository }}
          - **Commit:** ${{ github.sha }}
          - **Branch:** ${{ github.ref_name }}

          _Esta issue fue creada automáticamente por CI/CD._
          EOF
      - name: Create issue from file
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🚨 Deployment failed on main branch"
          content-filepath: my-issue.md
          labels: |
            bug
            deployment-failure
